#' Number Events
#' Generate unique identifiers for each event, based on indicator of being in an event.
#' Nonevent periods are labelled NA
#' @param event_indicator A binary vector, where TRUE indicates an event
#' @export
number_events <- function(event_indicator){
  runs <- rle(event_indicator)
  event_num <- rep(seq_along(runs$lengths),runs$lengths)
  event_num[event_indicator==FALSE]=NA
  
  return(event_num)
}

#' Summarize Events
#' 
#' Generate basic event summaries
#' @param event_num an event identifer as generated by \link{number_events}
#' @param sample_interval the sample interval in seconds
#' @export
summarize_events <- function(event_num, sample_interval){
  nevents <- length(unique(event_num[!is.na(event_num)]))
  duration <- sum((!is.na(event_num))*sample_interval)/60
  return(list(nevents=nevents,duration=duration))
}